export type StyleTemplate = {
  id: string;
  name: string;
  description: string;
  family: "PHYSICAL" | "LIVE ACTION" | "ILLUSTRATION" | "3D" | "GRAPHIC";
  visualMedium: string;
  material: string;
  characters: string;
  environment: string;
  realism: string;
  stylisation: string;
  texture: string;
  colour: string;
  lighting: string;
  camera: string;
  lens: string;
  depth: string;
  composition: string;
  motion: string;
  faces: string;
  production: string;
  continuity: string;
  recipe: string;
  negative: string;
  use: string;
  weaknesses: string;
  critic: string;
};

export const STYLE_TEMPLATES: StyleTemplate[] = [
  {
    id: "cinematic-miniature-claymation",
    name: "Cinematic Miniature Claymation",
    description: "Handcrafted clay characters on miniature sets, lit like a stop-motion film.",
    family: "PHYSICAL",
    visualMedium: "Stop-motion claymation",
    material: "Visible clay, fingerprints, small tool marks",
    characters: "Expressive clay people, slightly exaggerated faces, not smooth toys",
    environment: "Miniature physical sets with real scale cues",
    realism: "Physical miniature",
    stylisation: "High, handmade",
    texture: "Clay grain and fingerprints",
    colour: "Rich, practical, not neon",
    lighting: "Cinematic practical light on a small set",
    camera: "Locked, deliberate, filmic",
    lens: "Short telephoto feel, shallow where useful",
    depth: "Shallow on the subject, set still readable",
    composition: "Strong environmental storytelling",
    motion: "Pose-to-pose stop motion",
    faces: "Expressive, slightly exaggerated, sculpted",
    production: "Premium stop-motion, not a kids show",
    continuity: "Same clay identity, wardrobe, and set. Pose may change.",
    recipe: "Photograph a handmade clay miniature. Fingerprints stay. Practical cinematic light. Premium stop-motion, not CGI.",
    negative: "No generic 3D cartoon. No smooth plastic. No cheap children's animation. No glossy CGI.",
    use: "Character comedy, visual metaphor, tactile stories",
    weaknesses: "Fine readable text and perfect likenesses",
    critic: "Visible tactile clay is expected. Smooth plastic or glossy CGI is a STYLE MATCH failure.",
  },
  {
    id: "cineplastic",
    name: "CinePlastic",
    description: "Premium stylised 3D with a physical toy diorama finish.",
    family: "3D",
    visualMedium: "Stylised 3D diorama",
    material: "Clean sculptural forms, intentional plastic and resin",
    characters: "Designed figurines, controlled proportions, not babies",
    environment: "Deliberately built miniature world",
    realism: "Stylised physical",
    stylisation: "High, controlled",
    texture: "Smooth sculpted surfaces with cinematic wear where designed",
    colour: "Strong colour separation",
    lighting: "High-end cinematic, not game-engine flat",
    camera: "Designed, graphic, cinematic",
    lens: "Clean, moderate depth",
    depth: "Subject separated, world still designed",
    composition: "Sculptural, readable silhouette",
    motion: "Premium animation-film",
    faces: "Designed, readable, not chibi",
    production: "Animation-film finish",
    continuity: "Same sculpt and palette. Pose may change.",
    recipe: "Premium stylised 3D toy diorama. Clean sculpt, cinematic light, strong colour. Physical miniature, not a mobile game.",
    negative: "No generic Pixar copy. No cheap mobile-game CGI. No childish proportions. No random glossy AI plastic.",
    use: "Stylised product-world stories, graphic comedy",
    weaknesses: "Can look synthetic if the light goes flat",
    critic: "Sculptural plastic is expected. Do not fail the material for looking synthetic. Fail cheap game CGI and childish proportions.",
  },
  {
    id: "nineties-comic",
    name: "90s Comic",
    description: "Bold ink, halftone, and panel energy from a printed graphic novel.",
    family: "ILLUSTRATION",
    visualMedium: "Printed comic illustration",
    material: "Ink and halftone print",
    characters: "Exaggerated readable expressions, graphic faces",
    environment: "Drawn sets with graphic shadows",
    realism: "Graphic",
    stylisation: "High",
    texture: "Halftone dots, ink, paper print",
    colour: "Punchy, limited, printed",
    lighting: "Graphic shadow shapes, not photographic",
    camera: "Panel-like, dynamic",
    lens: "Flat graphic, not a photo lens",
    depth: "Designed overlap, not photo bokeh",
    composition: "Strong panel composition and contrast",
    motion: "Implied action, held poses",
    faces: "Exaggerated and immediately readable",
    production: "90s graphic-novel page",
    continuity: "Same ink faces and print texture. Expression may change.",
    recipe: "Bold ink outlines, halftone, printed paper, punchy colour, graphic shadows, 90s graphic-novel energy.",
    negative: "No clean modern vector. No generic superhero imitation. No flat corporate illustration.",
    use: "Jokes, contrast, social observation",
    weaknesses: "Subtle realism and small text",
    critic: "Ink and halftone are expected. Clean vector or corporate flat illustration is a STYLE MATCH failure.",
  },
  {
    id: "australian-indie-35mm",
    name: "Australian Indie 35mm",
    description: "A believable Australian film frame. Ordinary people, lived-in rooms, restrained grade.",
    family: "LIVE ACTION",
    visualMedium: "Live-action 35mm",
    material: "Real skin, fabric, dust, worn paint",
    characters: "Ordinary believable casting. Imperfect teeth, skin, and hair. Natural posture.",
    environment: "Lived-in Australian suburb, not a set catalogue",
    realism: "High",
    stylisation: "Low",
    texture: "Subtle 35mm grain, natural skin",
    colour: "Restrained grade, not teal-orange advertising",
    lighting: "Practical and natural. No beauty light.",
    camera: "Slightly imperfect framing where it feels observed",
    lens: "Normal to short telephoto. Limited bokeh.",
    depth: "Readable rooms. Not a portrait smear.",
    composition: "Observed, not staged-ad",
    motion: "Natural human movement",
    faces: "Ordinary. Not perfected.",
    production: "Australian indie film",
    continuity: "Same person, clothes, and place. Performance may change.",
    recipe: "Believable Australian 35mm frame. Ordinary casting, natural skin, lived-in suburb, practical light, subtle grain, restrained colour.",
    negative: "No glossy AI ad. No HDR glow. No beauty lighting. No plastic skin. No luxury polish. No hyper-clean surfaces. No excessive golden hour. No overly perfect actors.",
    use: "Human stories, recognition, quiet comedy",
    weaknesses: "Stylised metaphor and graphic jokes",
    critic: "Plastic skin, HDR glow, beauty light, and generic commercial polish are STYLE MATCH failures. Ordinary skin, teeth, hair, and imperfect framing are not failures.",
  },
  {
    id: "handcrafted-stop-motion",
    name: "Handcrafted Stop-Motion Miniature",
    description: "Fabric, felt, yarn, and stitched puppets on miniature sets.",
    family: "PHYSICAL",
    visualMedium: "Fabric stop-motion",
    material: "Fabric, felt, yarn, stitches, handmade props",
    characters: "Constructed puppets, visible seams",
    environment: "Miniature physical sets",
    realism: "Physical miniature",
    stylisation: "High, handmade",
    texture: "Fibre, stitch, cloth",
    colour: "Dyed fabric, practical",
    lighting: "Practical miniature light",
    camera: "Stop-motion film frame",
    lens: "Close, tactile",
    depth: "Shallow on the puppet, set still handmade",
    composition: "Tabletop theatre",
    motion: "Stop motion",
    faces: "Stitched or constructed, expressive",
    production: "Handmade puppet film",
    continuity: "Same puppet and set. Gesture may change.",
    recipe: "Physical puppet of fabric, felt, and yarn. Stitches visible. Miniature set. Practical light. Not clay and not CGI.",
    negative: "No pure claymation. No smooth CGI. No digital cartoon.",
    use: "Tender or odd handmade stories",
    weaknesses: "Photoreal people and tiny type",
    critic: "Fabric, felt, yarn, or stitches are expected. Clay or smooth CGI is a STYLE MATCH failure.",
  },
  {
    id: "graphic-collage",
    name: "Graphic Collage",
    description: "Torn paper, print, tape, and type layered into one editorial picture.",
    family: "GRAPHIC",
    visualMedium: "Editorial collage",
    material: "Torn paper, newsprint, tape, photo scraps, ink",
    characters: "Cut-out or drawn figures inside the collage",
    environment: "Layered paper world, not a clean room render",
    realism: "Mixed",
    stylisation: "High",
    texture: "Paper fibre, print, tape, scribble",
    colour: "Ink, newsprint, a few strong hits",
    lighting: "Flat scan plus small paper shadows",
    camera: "Straight-on editorial",
    lens: "No photographic lens look",
    depth: "Layers, not bokeh",
    composition: "Bold juxtaposition, controlled mess",
    motion: "Layers shifting",
    faces: "Graphic, cut, or drawn",
    production: "Editorial design",
    continuity: "Same paper language and characters. Arrangement may change.",
    recipe: "Torn paper, newsprint, tape, photo scraps, scribbles, and handwritten marks in one layered editorial collage.",
    negative: "No simple split-screen photo. No clean Canva layout. No generic scrapbook.",
    use: "Ideas, headlines, contrast, commentary",
    weaknesses: "Subtle acting and realistic rooms",
    critic: "Torn paper, print, and layering are expected. A clean split photo or a tidy template collage is a STYLE MATCH failure.",
  },
  {
    id: "painted-editorial",
    name: "Illustrated Storybook / Painted Editorial",
    description: "Hand-painted editorial pictures. Brush texture, imperfect surfaces, not anime.",
    family: "ILLUSTRATION",
    visualMedium: "Painted illustration",
    material: "Paint, brush, paper",
    characters: "Expressive painted people, specific not pretty",
    environment: "Warm, detailed, imperfect places",
    realism: "Illustrated realism",
    stylisation: "Medium-high",
    texture: "Visible brush, not vector",
    colour: "Rich, slightly dirty, painterly",
    lighting: "Painterly light, not a render",
    camera: "Storybook framing, editorial",
    lens: "Painted depth, not a photo lens",
    depth: "Designed, readable",
    composition: "One clear story picture",
    motion: "Held illustrated moments",
    faces: "Expressive, painted, not anime",
    production: "Editorial storybook",
    continuity: "Same painted people and world. Expression may change.",
    recipe: "Hand-painted editorial illustration. Visible brush, imperfect surfaces, painterly light, specific characters. Not anime and not vector.",
    negative: "No generic anime. No generic 3D. No simple children's picture book. No smooth digital vector.",
    use: "Story, warmth, character comedy",
    weaknesses: "Can drift into pretty digital painting",
    critic: "Visible paint and brush are expected. Anime, smooth vector, or 3D is a STYLE MATCH failure.",
  },
  {
    id: "retro-anime",
    name: "Retro Anime / Manga Cinematic",
    description: "Cinematic anime-film frames. Detailed worlds, film texture, not a cheap avatar.",
    family: "ILLUSTRATION",
    visualMedium: "Cinematic anime illustration",
    material: "Ink line, paint, film grain",
    characters: "Emotionally readable, detailed, not chibi",
    environment: "Detailed illustrated places",
    realism: "Illustrated",
    stylisation: "High, cinematic",
    texture: "Line, grain, painted light",
    colour: "Warm and cool cinematic contrast",
    lighting: "Film light, motivated",
    camera: "Anime-film framing",
    lens: "Illustrated cinematic",
    depth: "Background detail remains",
    composition: "Emotional and environmental",
    motion: "Anime-film holds",
    faces: "Expressive line, not an avatar",
    production: "Feature-anime frame",
    continuity: "Same designs and line. Expression may change.",
    recipe: "Cinematic anime-film frame. Detailed environment, expressive line, film texture, warm and cool light. Not a cheap avatar.",
    negative: "No cheap anime avatar. No flat cel game art. No chibi.",
    use: "Emotion, atmosphere, stylised story",
    weaknesses: "Can look generic if the line goes soft",
    critic: "Cinematic anime line and a detailed world are expected. Chibi, flat game cel, or a generic avatar is a STYLE MATCH failure.",
  },
  {
    id: "layered-papercraft",
    name: "Layered Papercraft",
    description: "Flat cut cardstock, stacked into a tabletop theatre. Not a 3D model with paper stuck on.",
    family: "PHYSICAL",
    visualMedium: "Photographed paper diorama",
    material: "Cardstock, cut edges, paper fibre",
    characters: "Flat cut figures, hinged limbs, printed flat faces",
    environment: "Stacked flat scenery",
    realism: "Physical paper",
    stylisation: "High, constructed",
    texture: "Paper fibre, cut edge, matte card",
    colour: "Printed inks on card",
    lighting: "Small real shadows between layers",
    camera: "Straight photograph of a tabletop theatre",
    lens: "Normal, little blur",
    depth: "Shadows between sheets, not rounded volume",
    composition: "Layered flats, readable silhouette",
    motion: "Hinged paper movement",
    faces: "Flat printed features",
    production: "Handmade paper theatre, photographed",
    continuity: "Same cut characters and layers. Hinge pose may change.",
    recipe: "Flat 2D cut cardstock stacked in layers. Visible cut edges and paper fibre. Hinged limbs. Printed flat faces. Small shadows between sheets. Photographed tabletop theatre.",
    negative: "No rounded 3D models. No clay. No smooth CGI. No 3D animation with a paper texture.",
    use: "Graphic stories, clear metaphor, handmade comedy",
    weaknesses: "Rounded forms and realistic skin",
    critic: "Flat layered cardstock is expected. Rounded CGI, clay, or a 3D model with paper texture is a STYLE MATCH failure.",
  },
];

export function styleById(id: string) {
  return STYLE_TEMPLATES.find((style) => style.id === id);
}

export function compileStylePrompt(style: StyleTemplate, scene: string) {
  return [`Style: ${style.name}.`, `Medium: ${style.visualMedium}.`, style.recipe, `Scene: ${scene}`, `Negative: ${style.negative}`].join("\n");
}

export function styleCriticRules(styleId: string) {
  return styleById(styleId)?.critic ?? "Judge the image against the selected style bible. Do not use one universal look.";
}
