import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { chooseContentStyle } from "@/lib/actions";
import { getDb } from "@/lib/db/client";

export const metadata: Metadata = { title: "Choose the look" };

export default async function ChooseLookPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ family?: string }> }) {
  const { id } = await params;
  const filters = await searchParams;
  const db = getDb();
  const item = db.prepare(`SELECT id, title, brand, stage FROM content_items WHERE id = ?`).get(id) as { id: string; title: string | null; brand: string | null; stage: string } | undefined;
  if (!item) notFound();
  const styles = db.prepare(`SELECT id, name, description, visual_medium, family, recommended_use FROM style_templates WHERE status = 'approved' ${filters.family ? "AND family = ?" : ""} ORDER BY name`).all(...(filters.family ? [filters.family] : [])) as Array<{
    id: string;
    name: string;
    description: string;
    visual_medium: string | null;
    family: string;
    recommended_use: string | null;
  }>;
  const families = ["PHYSICAL", "LIVE ACTION", "ILLUSTRATION", "3D", "GRAPHIC", "CUSTOM"];

  return (
    <article>
      <header className="page-header">
        <p className="kicker">{item.brand}</p>
        <h1>Choose the look</h1>
        <p className="lede">{item.title}. Pick from the picture of the style, not a dropdown. No storyboard is generated by this choice.</p>
        <p className="row-actions">
          {families.map((family) => (
            <Link key={family} href={`/production/content/${id}/look?family=${encodeURIComponent(family)}`}>{family}</Link>
          ))}
        </p>
      </header>
      {styles.map((style) => (
        <section className="card" key={style.id}>
          <p className="kicker">REFERENCE REQUIRED</p>
          <h2>{style.name}</h2>
          <p>{style.description}</p>
          <p className="quiet">{style.visual_medium}. {style.recommended_use}</p>
          <form action={chooseContentStyle}>
            <input type="hidden" name="contentId" value={id} />
            <input type="hidden" name="styleId" value={style.id} />
            <button type="submit">Use this style</button>
          </form>
        </section>
      ))}
    </article>
  );
}
